const en = {
  appName: "Xpenzie",
  tabAll: "All",
  tabMonthly: "Monthly",
  tabYearly: "Yearly",
  tabSettings: "Settings",
  totIncome: "Total Income: ",
  totExpenditure: "Total Expenditure: ",
  savings: "Savings: ",
  expenditure: "Expenditure",
  income: "Income",
  expName: "Enter expense name",
  incName: "Enter income name",
  amount: "Amount",
  categoryPlaceholder: "Category...",
  searchPlaceholder: "Search...",
  closeBtn: "Close",
  confirmBtn: "Confirm",
  saveBtn: "Save",
  selectCurrency: "Select Currency:",
  deletePrompt: "Are you sure you want to delete the entry?",
  deleteBtn: "Delete",
  cancelBtn: "Cancel",
  selectLanguage: "Select Language:",
  monthIncome: "Income: ",
  monthExpenditure: "Expenditure: ",
  account: "Account",
  firstName: "First Name",
  lastName: "Last Name",
  currency: "Currency",
  bkpnrstr: "Backup & Restore",
  notification: "Notification",
  language: "Language",
  security: "Security",
  feedback: "Feedback",
  pdf: "PDF",
  pdfAllTitle: "Complete Transactions Summary",
  pdfMonthlyTitle: "Monthly Transactions Summary",
  pdfYearlyTitle: "Yearly Transactions Summary",
  appFooter: "Xpenzie v0.8.0",
};

const hi = {
  tabAll: "सभी",
  tabMonthly: "मासिक",
  tabYearly: "वार्षिक",
  tabSettings: "सेटिंग्स",
  totIncome: "कुल आय: ",
  totExpenditure: "कुल खर्च: ",
  savings: "बचत: ",
  expenditure: "खर्च",
  income: "आय",
  expName: "खर्च का नाम दर्ज करें",
  incName: "आय का नाम दर्ज करें",
  amount: "राशि",
  categoryPlaceholder: "श्रेणी...",
  searchPlaceholder: "खोजें...",
  closeBtn: "बंद करें",
  confirmBtn: "पुष्टि करें",
  saveBtn: "सहेजें",
  selectCurrency: "मुद्रा चुनें:",
  deletePrompt: "क्या आप वाकई प्रविष्टि को हटाना चाहते हैं?",
  deleteBtn: "हटाएं",
  cancelBtn: "नहीं",
  selectLanguage: "भाषा चुनें:",
  monthIncome: "आय: ",
  monthExpenditure: "खर्च: ",
  account: "खाता",
  firstName: "पहला नाम",
  lastName: "अंतिम नाम",
  currency: "मुद्रा",
  bkpnrstr: "संचय और पुनर्स्थापना",
  notification: "सूचना",
  language: "भाषा",
  security: "सुरक्षा",
  feedback: "प्रतिक्रिया",
  pdfAllTitle: "संपूर्ण लेन-देन सारांश",
  pdfMonthlyTitle: "मासिक लेन-देन सारांश",
  pdfYearlyTitle: "वार्षिक लेन-देन सारांश",
};

const bn = {
  tabAll: "সব",
  tabMonthly: "মাসিক",
  tabYearly: "বার্ষিক",
  tabSettings: "সেটিংস",
  totIncome: "মোট আয়: ",
  totExpenditure: "মোট ব্যয়: ",
  savings: "সঞ্চয়: ",
  expenditure: "ব্যয়",
  income: "আয়",
  expName: "ব্যয়ের নাম লিখুন",
  incName: "আয়ের নাম লিখুন",
  amount: "পরিমাণ",
  categoryPlaceholder: "বিভাগ...",
  searchPlaceholder: "অনুসন্ধান করুন...",
  closeBtn: "বন্ধ করুন",
  confirmBtn: "নিশ্চিত করুন",
  saveBtn: "সংরক্ষণ করুন",
  selectCurrency: "মুদ্রা নির্বাচন করুন:",
  deletePrompt: "আপনি কি সত্যিই এন্ট্রিটি মুছে ফেলতে চান?",
  deleteBtn: "হাঁ",
  cancelBtn: "না",
  selectLanguage: "ভাষা নির্বাচন করুন:",
  monthIncome: "আয়: ",
  monthExpenditure: "ব্যয়: ",
  account: "অ্যাকাউন্ট",
  firstName: "প্রথম নাম",
  lastName: "শেষ নাম",
  currency: "মুদ্রা",
  bkpnrstr: "ব্যাকআপ এবং পুনরুদ্ধার",
  notification: "বিজ্ঞপ্তি",
  language: "ভাষা",
  security: "নিরাপত্তা",
  feedback: "মতামত",
  pdfAllTitle: "সম্পূর্ণ লেনদেন সংক্ষেপ",
  pdfMonthlyTitle: "মাসিক লেনদেন সংক্ষেপ",
  pdfYearlyTitle: "বার্ষিক লেনদেন সংক্ষেপ",
};

const es = {
  tabAll: "Todos",
  tabMonthly: "Mensual",
  tabYearly: "Anual",
  tabSettings: "Configuración",
  totIncome: "Ingresos Totales: ",
  totExpenditure: "Gastos Totales: ",
  savings: "Ahorros: ",
  expenditure: "Gasto",
  income: "Ingreso",
  expName: "Ingrese el nombre del gasto",
  incName: "Ingrese el nombre del ingreso",
  amount: "Cantidad",
  categoryPlaceholder: "Categoría...",
  searchPlaceholder: "Buscar...",
  closeBtn: "Cerrar",
  confirmBtn: "Confirmar",
  saveBtn: "Guardar",
  selectCurrency: "Seleccionar Moneda:",
  deletePrompt: "¿Está seguro de que desea eliminar la entrada?",
  deleteBtn: "Eliminar",
  cancelBtn: "Cancelar",
  selectLanguage: "Seleccionar Idioma:",
  monthIncome: "Ingresos: ",
  monthExpenditure: "Gastos: ",
  account: "Cuenta",
  firstName: "Nombre",
  lastName: "Apellido",
  currency: "Moneda",
  bkpnrstr: "Copia de Seguridad y Restauración",
  notification: "Notificación",
  language: "Idioma",
  security: "Seguridad",
  feedback: "Comentarios",
  pdfAllTitle: "Resumen completo de transacciones",
  pdfMonthlyTitle: "Resumen mensual de transacciones",
  pdfYearlyTitle: "Resumen anual de transacciones",
};

const fr = {
  tabAll: "Tous",
  tabMonthly: "Mensuel",
  tabYearly: "Annuel",
  tabSettings: "Paramètres",
  totIncome: "Revenu Total: ",
  totExpenditure: "Dépense Totale: ",
  savings: "Économies: ",
  expenditure: "Dépense",
  income: "Revenu",
  expName: "Entrez le nom de la dépense",
  incName: "Entrez le nom du revenu",
  amount: "Montant",
  categoryPlaceholder: "Catégorie...",
  searchPlaceholder: "Rechercher...",
  closeBtn: "Fermer",
  confirmBtn: "Confirmer",
  saveBtn: "Enregistrer",
  selectCurrency: "Sélectionner la Devise:",
  deletePrompt: "Êtes-vous sûr de vouloir supprimer l'entrée ?",
  deleteBtn: "Supprimer",
  cancelBtn: "Annuler",
  selectLanguage: "Sélectionner la Langue:",
  monthIncome: "Revenu: ",
  monthExpenditure: "Dépense: ",
  account: "Compte",
  firstName: "Prénom",
  lastName: "Nom",
  currency: "Devise",
  bkpnrstr: "Sauvegarde et Restauration",
  notification: "Notification",
  language: "Langue",
  security: "Sécurité",
  feedback: "Commentaires",
  pdfAllTitle: "Résumé complet des transactions",
  pdfMonthlyTitle: "Résumé mensuel des transactions",
  pdfYearlyTitle: "Résumé annuel des transactions",
};

const ru = {
  tabAll: "Все",
  tabMonthly: "Ежемесячно",
  tabYearly: "Ежегодно",
  tabSettings: "Настройки",
  totIncome: "Общий Доход: ",
  totExpenditure: "Общий Расход: ",
  savings: "Сбережения: ",
  expenditure: "Расход",
  income: "Доход",
  expName: "Введите название расхода",
  incName: "Введите название дохода",
  amount: "Сумма",
  categoryPlaceholder: "Категория...",
  searchPlaceholder: "Поиск...",
  closeBtn: "Закрыть",
  confirmBtn: "Подтвердить",
  saveBtn: "Сохранить",
  selectCurrency: "Выберите Валюту:",
  deletePrompt: "Вы уверены, что хотите удалить запись?",
  deleteBtn: "Удалить",
  cancelBtn: "Отмена",
  selectLanguage: "Выберите Язык:",
  monthIncome: "Доход: ",
  monthExpenditure: "Расход: ",
  account: "Аккаунт",
  firstName: "Имя",
  lastName: "Фамилия",
  currency: "Валюта",
  bkpnrstr: "Резервное копирование и восстановление",
  notification: "Уведомление",
  language: "Язык",
  security: "Безопасность",
  feedback: "Обратная связь",
  pdfAllTitle: "Полный обзор транзакций",
  pdfMonthlyTitle: "Ежемесячный обзор транзакций",
  pdfYearlyTitle: "Ежегодный обзор транзакций",
};

const ja = {
  tabAll: "すべて",
  tabMonthly: "月次",
  tabYearly: "年次",
  tabSettings: "設定",
  totIncome: "総収入: ",
  totExpenditure: "総支出: ",
  savings: "貯金: ",
  expenditure: "支出",
  income: "収入",
  expName: "支出の名前を入力してください",
  incName: "収入の名前を入力してください",
  amount: "金額",
  categoryPlaceholder: "カテゴリ...",
  searchPlaceholder: "検索...",
  closeBtn: "閉じる",
  confirmBtn: "確認",
  saveBtn: "保存",
  selectCurrency: "通貨を選択:",
  deletePrompt: "エントリを削除してもよろしいですか？",
  deleteBtn: "削除",
  cancelBtn: "キャンセル",
  selectLanguage: "言語を選択:",
  monthIncome: "収入: ",
  monthExpenditure: "支出: ",
  account: "アカウント",
  firstName: "名",
  lastName: "姓",
  currency: "通貨",
  bkpnrstr: "バックアップと復元",
  notification: "通知",
  language: "言語",
  security: "セキュリティ",
  feedback: "フィードバック",
  pdfAllTitle: "全取引の概要",
  pdfMonthlyTitle: "月次取引の概要",
  pdfYearlyTitle: "年次取引の概要",
};

export { en, hi, bn, es, fr, ru, ja };
