import Constants from "expo-constants";

const appVersion = Constants.expoConfig.version;

const en = {
  appName: "Xpenzie",
  tabAll: "All",
  tabMonthly: "Monthly",
  tabYearly: "Yearly",
  tabSettings: "Settings",
  totIncome: "Total Income: ",
  totExpenditure: "Total Expenditure: ",
  savings: "Savings: ",
  expenditure: "Expenditure",
  income: "Income",
  expName: "Enter expense name",
  incName: "Enter income name",
  amount: "Amount",
  categoryPlaceholder: "Category...",
  searchPlaceholder: "Search...",
  closeBtn: "Close",
  confirmBtn: "Confirm",
  saveBtn: "Save",
  selectCurrency: "Select Currency:",
  deletePrompt: "Are you sure you want to delete the entry?",
  deleteBtn: "Delete",
  cancelBtn: "Cancel",
  selectLanguage: "Select Language:",
  monthIncome: "Income: ",
  monthExpenditure: "Expenditure: ",
  account: "Account",
  name: "Name",
  firstName: "First Name",
  lastName: "Last Name",
  email: "Email",
  message: "Message",
  send: "Send",
  success: "Success",
  error: "Error",
  feedbackSuccess:
    "Your message has been successfully sent. We will get back to you as soon as possible.",
  feedbackError:
    "Oops! Something went wrong while sending your message. Please try again later or write a mail at prathamj0502@gmail.com.",
  currency: "Currency",
  bkpnrstr: "Backup & Restore",
  notification: "Notification",
  language: "Language",
  security: "Security",
  feedback: "Feedback & Support",
  theme: "Theme",
  selectTheme: "Select Theme:",
  default: "Royal Amethyst",
  snow: "Snow",
  dracula: "Dracula",
  pdf: "PDF",
  pdfAllTitle: "Complete Transactions Summary",
  pdfMonthlyTitle: "Monthly Transactions Summary",
  pdfYearlyTitle: "Yearly Transactions Summary",
  enableBiometric: "Enable Biometric Authentication:",
  noBiometricSupported: "No biometric supported",
  noBiometricEnrolled: "No biometrics enrolled",
  alert: "Alert",
  appFooter: `Xpenzie ${appVersion}`,
};

const hi = {
  tabAll: "सभी",
  tabMonthly: "मासिक",
  tabYearly: "वार्षिक",
  tabSettings: "सेटिंग्स",
  totIncome: "कुल आय: ",
  totExpenditure: "कुल खर्च: ",
  savings: "बचत: ",
  expenditure: "खर्च",
  income: "आय",
  expName: "खर्च का नाम दर्ज करें",
  incName: "आय का नाम दर्ज करें",
  amount: "राशि",
  categoryPlaceholder: "श्रेणी...",
  searchPlaceholder: "खोजें...",
  closeBtn: "बंद करें",
  confirmBtn: "पुष्टि करें",
  saveBtn: "सहेजें",
  selectCurrency: "मुद्रा चुनें:",
  deletePrompt: "क्या आप वाकई प्रविष्टि को हटाना चाहते हैं?",
  deleteBtn: "हटाएं",
  cancelBtn: "नहीं",
  selectLanguage: "भाषा चुनें:",
  monthIncome: "आय: ",
  monthExpenditure: "खर्च: ",
  account: "खाता",
  name: "नाम",
  firstName: "पहला नाम",
  lastName: "अंतिम नाम",
  email: "ईमेल",
  message: "संदेश",
  send: "भेजें",
  success: "सफलता",
  error: "त्रुटि",
  feedbackSuccess:
    "आपका संदेश सफलतापूर्वक भेज दिया गया है। हम जल्द से जल्द आपसे संपर्क करेंगे।",
  feedbackError:
    "उफ़! आपका संदेश भेजने में कुछ गलती हो गई। कृपया बाद में पुनः प्रयास करें या prathamj0502@gmail.com पर मेल करें।",
  currency: "मुद्रा",
  bkpnrstr: "संचय और पुनर्स्थापना",
  notification: "सूचना",
  language: "भाषा",
  security: "सुरक्षा",
  feedback: "प्रतिक्रिया और समर्थन",
  theme: "थीम",
  selectTheme: "थीम चुनें:",
  default: "रॉयल एमथिस्ट",
  snow: "बर्फ",
  dracula: "ड्रैकुला",
  pdfAllTitle: "संपूर्ण लेन-देन सारांश",
  pdfMonthlyTitle: "मासिक लेन-देन सारांश",
  pdfYearlyTitle: "वार्षिक लेन-देन सारांश",
  enableBiometric: "बायोमेट्रिक प्रमाणीकरण सक्षम करें:",
  noBiometricSupported: "कोई बायोमैट्रिक समर्थित नहीं",
  noBiometricEnrolled: "कोई बायोमेट्रिक नामांकित नहीं",
  alert: "चेतावनी",
};

const bn = {
  tabAll: "সব",
  tabMonthly: "মাসিক",
  tabYearly: "বার্ষিক",
  tabSettings: "সেটিংস",
  totIncome: "মোট আয়: ",
  totExpenditure: "মোট ব্যয়: ",
  savings: "সঞ্চয়: ",
  expenditure: "ব্যয়",
  income: "আয়",
  expName: "ব্যয়ের নাম লিখুন",
  incName: "আয়ের নাম লিখুন",
  amount: "পরিমাণ",
  categoryPlaceholder: "বিভাগ...",
  searchPlaceholder: "অনুসন্ধান করুন...",
  closeBtn: "বন্ধ করুন",
  confirmBtn: "নিশ্চিত করুন",
  saveBtn: "সংরক্ষণ করুন",
  selectCurrency: "মুদ্রা নির্বাচন করুন:",
  deletePrompt: "আপনি কি সত্যিই এন্ট্রিটি মুছে ফেলতে চান?",
  deleteBtn: "হাঁ",
  cancelBtn: "না",
  selectLanguage: "ভাষা নির্বাচন করুন:",
  monthIncome: "আয়: ",
  monthExpenditure: "ব্যয়: ",
  account: "অ্যাকাউন্ট",
  name: "নাম",
  firstName: "প্রথম নাম",
  lastName: "শেষ নাম",
  email: "ইমেল",
  message: "বার্তা",
  send: "প্রেরণ করুন",
  success: "সফলতা",
  error: "ত্রুটি",
  feedbackSuccess:
    "আপনার বার্তাটি সফলভাবে পাঠানো হয়েছে। আমরা যত তাড়াতাড়ি সম্ভব আপনার সাথে যোগাযোগ করব।",
  feedbackError:
    "উফ! আপনার বার্তা পাঠানোর সময় কিছু ভুল হয়েছে। দয়া করে পরে আবার চেষ্টা করুন অথবা prathamj0502@gmail.com -এ একটি মেইল ​​লিখুন।",
  currency: "মুদ্রা",
  bkpnrstr: "ব্যাকআপ এবং পুনরুদ্ধার",
  notification: "বিজ্ঞপ্তি",
  language: "ভাষা",
  security: "নিরাপত্তা",
  feedback: "মতামত এবং সমর্থন",
  theme: "থিম",
  selectTheme: "থিম নির্বাচন করুন:",
  default: "রয়াল এমথিস্ট",
  snow: "বরফ",
  dracula: "ড্রাকুলা",
  pdfAllTitle: "সম্পূর্ণ লেনদেন সংক্ষেপ",
  pdfMonthlyTitle: "মাসিক লেনদেন সংক্ষেপ",
  pdfYearlyTitle: "বার্ষিক লেনদেন সংক্ষেপ",
  enableBiometric: "বায়োমেট্রিক প্রমাণীকরণ সক্ষম করুন:",
  noBiometricSupported: "কোনো বায়োমেট্রিক সমর্থিত নয়",
  noBiometricEnrolled: "কোনো বায়োমেট্রিক নামাংকিত নয়",
  alert: "সতর্কতা",
};

const es = {
  tabAll: "Todos",
  tabMonthly: "Mensual",
  tabYearly: "Anual",
  tabSettings: "Configuración",
  totIncome: "Ingresos Totales: ",
  totExpenditure: "Gastos Totales: ",
  savings: "Ahorros: ",
  expenditure: "Gasto",
  income: "Ingreso",
  expName: "Ingrese el nombre del gasto",
  incName: "Ingrese el nombre del ingreso",
  amount: "Cantidad",
  categoryPlaceholder: "Categoría...",
  searchPlaceholder: "Buscar...",
  closeBtn: "Cerrar",
  confirmBtn: "Confirmar",
  saveBtn: "Guardar",
  selectCurrency: "Seleccionar Moneda:",
  deletePrompt: "¿Está seguro de que desea eliminar la entrada?",
  deleteBtn: "Eliminar",
  cancelBtn: "Cancelar",
  selectLanguage: "Seleccionar Idioma:",
  monthIncome: "Ingresos: ",
  monthExpenditure: "Gastos: ",
  account: "Cuenta",
  name: "Nombre",
  firstName: "Nombre",
  lastName: "Apellido",
  email: "Correo Electrónico",
  message: "Mensaje",
  send: "Enviar",
  success: "Éxito",
  error: "Error",
  feedbackSuccess:
    "Su mensaje ha sido enviado con éxito. Nos pondremos en contacto con usted lo antes posible.",
  feedbackError:
    "¡Ups! Algo salió mal al enviar su mensaje. Por favor, inténtelo de nuevo más tarde o escriba un correo a prathamj0502@gmail.com.",
  currency: "Moneda",
  bkpnrstr: "Copia de Seguridad y Restauración",
  notification: "Notificación",
  language: "Idioma",
  security: "Seguridad",
  feedback: "Comentarios y Soporte",
  theme: "Tema",
  selectTheme: "Seleccionar Tema:",
  default: "Amatista Real",
  snow: "Nieve",
  dracula: "Drácula",
  pdfAllTitle: "Resumen completo de transacciones",
  pdfMonthlyTitle: "Resumen mensual de transacciones",
  pdfYearlyTitle: "Resumen anual de transacciones",
  enableBiometric: "Habilitar Autenticación Biométrica:",
  noBiometricSupported: "No se admite biometría",
  noBiometricEnrolled: "No se han registrado biometrías",
  alert: "Alerta",
};

const fr = {
  tabAll: "Tous",
  tabMonthly: "Mensuel",
  tabYearly: "Annuel",
  tabSettings: "Paramètres",
  totIncome: "Revenu Total: ",
  totExpenditure: "Dépense Totale: ",
  savings: "Économies: ",
  expenditure: "Dépense",
  income: "Revenu",
  expName: "Entrez le nom de la dépense",
  incName: "Entrez le nom du revenu",
  amount: "Montant",
  categoryPlaceholder: "Catégorie...",
  searchPlaceholder: "Rechercher...",
  closeBtn: "Fermer",
  confirmBtn: "Confirmer",
  saveBtn: "Enregistrer",
  selectCurrency: "Sélectionner la Devise:",
  deletePrompt: "Êtes-vous sûr de vouloir supprimer l'entrée ?",
  deleteBtn: "Supprimer",
  cancelBtn: "Annuler",
  selectLanguage: "Sélectionner la Langue:",
  monthIncome: "Revenu: ",
  monthExpenditure: "Dépense: ",
  account: "Compte",
  name: "Nom",
  firstName: "Prénom",
  lastName: "Nom",
  email: "Email",
  message: "Message",
  send: "Envoyer",
  success: "Succès",
  error: "Erreur",
  feedbackSuccess:
    "Votre message a été envoyé avec succès. Nous vous contacterons dès que possible.",
  feedbackError:
    "Oups ! Une erreur s'est produite lors de l'envoi de votre message. Veuillez réessayer plus tard ou écrire un mail à prathamj0502@gmail.com.",
  currency: "Devise",
  bkpnrstr: "Sauvegarde et Restauration",
  notification: "Notification",
  language: "Langue",
  security: "Sécurité",
  feedback: "Commentaires et Support",
  theme: "Thème",
  selectTheme: "Sélectionner le thème :",
  default: "Améthyste Royal",
  snow: "Neige",
  dracula: "Dracula",
  pdfAllTitle: "Résumé complet des transactions",
  pdfMonthlyTitle: "Résumé mensuel des transactions",
  pdfYearlyTitle: "Résumé annuel des transactions",
  enableBiometric: "Activer l'authentification biométrique:",
  noBiometricSupported: "Aucune biométrie prise en charge",
  noBiometricEnrolled: "Aucune biométrie enregistrée",
  alert: "Alerte",
};

const ru = {
  tabAll: "Все",
  tabMonthly: "Ежемесячно",
  tabYearly: "Ежегодно",
  tabSettings: "Настройки",
  totIncome: "Общий Доход: ",
  totExpenditure: "Общий Расход: ",
  savings: "Сбережения: ",
  expenditure: "Расход",
  income: "Доход",
  expName: "Введите название расхода",
  incName: "Введите название дохода",
  amount: "Сумма",
  categoryPlaceholder: "Категория...",
  searchPlaceholder: "Поиск...",
  closeBtn: "Закрыть",
  confirmBtn: "Подтвердить",
  saveBtn: "Сохранить",
  selectCurrency: "Выберите Валюту:",
  deletePrompt: "Вы уверены, что хотите удалить запись?",
  deleteBtn: "Удалить",
  cancelBtn: "Отмена",
  selectLanguage: "Выберите Язык:",
  monthIncome: "Доход: ",
  monthExpenditure: "Расход: ",
  account: "Аккаунт",
  name: "Имя",
  firstName: "Имя",
  lastName: "Фамилия",
  email: "Электронная почта",
  message: "Сообщение",
  send: "Отправить",
  success: "Успех",
  error: "Ошибка",
  feedbackSuccess:
    "Ваше сообщение успешно отправлено. Мы свяжемся с вами как можно скорее.",
  feedbackError:
    "Упс! Что-то пошло не так при отправке вашего сообщения. Пожалуйста, попробуйте позже или напишите на prathamj0502@gmail.com.",
  currency: "Валюта",
  bkpnrstr: "Резервное копирование и восстановление",
  notification: "Уведомление",
  language: "Язык",
  security: "Безопасность",
  feedback: "Обратная связь и Поддержка",
  theme: "Тема",
  selectTheme: "Выбрать тему:",
  default: "Королевский аметист",
  snow: "Снег",
  dracula: "Дракула",
  pdfAllTitle: "Полный обзор транзакций",
  pdfMonthlyTitle: "Ежемесячный обзор транзакций",
  pdfYearlyTitle: "Ежегодный обзор транзакций",
  enableBiometric: "Включить биометрическую аутентификацию:",
  noBiometricSupported: "Биометрия не поддерживается",
  noBiometricEnrolled: "Биометрия не зарегистрирована",
  alert: "Предупреждение",
};

const ja = {
  tabAll: "すべて",
  tabMonthly: "月次",
  tabYearly: "年次",
  tabSettings: "設定",
  totIncome: "総収入: ",
  totExpenditure: "総支出: ",
  savings: "貯金: ",
  expenditure: "支出",
  income: "収入",
  expName: "支出の名前を入力してください",
  incName: "収入の名前を入力してください",
  amount: "金額",
  categoryPlaceholder: "カテゴリ...",
  searchPlaceholder: "検索...",
  closeBtn: "閉じる",
  confirmBtn: "確認",
  saveBtn: "保存",
  selectCurrency: "通貨を選択:",
  deletePrompt: "エントリを削除してもよろしいですか？",
  deleteBtn: "削除",
  cancelBtn: "キャンセル",
  selectLanguage: "言語を選択:",
  monthIncome: "収入: ",
  monthExpenditure: "支出: ",
  account: "アカウント",
  name: "名前",
  firstName: "名",
  lastName: "姓",
  email: "メール",
  message: "メッセージ",
  send: "送信",
  success: "成功",
  error: "エラー",
  feedbackSuccess:
    "メッセージが正常に送信されました。できるだけ早くご連絡いたします。",
  feedbackError:
    "おっと！メッセージの送信中に問題が発生しました。後で再試行するか、prathamj0502@gmail.com にメールを書いてください。",
  currency: "通貨",
  bkpnrstr: "バックアップと復元",
  notification: "通知",
  language: "言語",
  security: "セキュリティ",
  feedback: "フィードバック＆サポート",
  theme: "テーマ",
  selectTheme: "テーマを選択:",
  default: "ロイヤルアメジスト",
  snow: "雪",
  dracula: "ドラキュラ",
  pdfAllTitle: "全取引の概要",
  pdfMonthlyTitle: "月次取引の概要",
  pdfYearlyTitle: "年次取引の概要",
  enableBiometric: "生体認証を有効にする:",
  noBiometricSupported: "生体認証がサポートされていません",
  noBiometricEnrolled: "生体認証が登録されていません",
  alert: "警告",
};

export { en, hi, bn, es, fr, ru, ja };
